// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/Clientmsg.proto

package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ServerTimeReq struct {
}

func (m *ServerTimeReq) Reset()                    { *m = ServerTimeReq{} }
func (m *ServerTimeReq) String() string            { return proto.CompactTextString(m) }
func (*ServerTimeReq) ProtoMessage()               {}
func (*ServerTimeReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type ServerTimeRsp struct {
	ServerTime uint64 `protobuf:"varint,1,opt,name=ServerTime" json:"ServerTime,omitempty"`
}

func (m *ServerTimeRsp) Reset()                    { *m = ServerTimeRsp{} }
func (m *ServerTimeRsp) String() string            { return proto.CompactTextString(m) }
func (*ServerTimeRsp) ProtoMessage()               {}
func (*ServerTimeRsp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *ServerTimeRsp) GetServerTime() uint64 {
	if m != nil {
		return m.ServerTime
	}
	return 0
}

type LoginReq struct {
	Id           uint64       `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Passwd       string       `protobuf:"bytes,2,opt,name=passwd" json:"passwd,omitempty"`
	OnlineStatue OnlineStatus `protobuf:"varint,3,opt,name=online_statue,json=onlineStatue,enum=rpc.OnlineStatus" json:"online_statue,omitempty"`
}

func (m *LoginReq) Reset()                    { *m = LoginReq{} }
func (m *LoginReq) String() string            { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()               {}
func (*LoginReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *LoginReq) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LoginReq) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

func (m *LoginReq) GetOnlineStatue() OnlineStatus {
	if m != nil {
		return m.OnlineStatue
	}
	return OnlineStatus_OS_ONLINE
}

type LoginRsp struct {
	Id         uint64     `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	ResultCode ResultCode `protobuf:"varint,2,opt,name=result_code,json=resultCode,enum=rpc.ResultCode" json:"result_code,omitempty"`
	ResultStr  string     `protobuf:"bytes,3,opt,name=result_str,json=resultStr" json:"result_str,omitempty"`
}

func (m *LoginRsp) Reset()                    { *m = LoginRsp{} }
func (m *LoginRsp) String() string            { return proto.CompactTextString(m) }
func (*LoginRsp) ProtoMessage()               {}
func (*LoginRsp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *LoginRsp) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LoginRsp) GetResultCode() ResultCode {
	if m != nil {
		return m.ResultCode
	}
	return ResultCode_RC_DEFAULT
}

func (m *LoginRsp) GetResultStr() string {
	if m != nil {
		return m.ResultStr
	}
	return ""
}

type LogoutReq struct {
	Id uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *LogoutReq) Reset()                    { *m = LogoutReq{} }
func (m *LogoutReq) String() string            { return proto.CompactTextString(m) }
func (*LogoutReq) ProtoMessage()               {}
func (*LogoutReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *LogoutReq) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type LogoutRsp struct {
	Id         uint64     `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	ResultCode ResultCode `protobuf:"varint,2,opt,name=result_code,json=resultCode,enum=rpc.ResultCode" json:"result_code,omitempty"`
	ResultStr  string     `protobuf:"bytes,3,opt,name=result_str,json=resultStr" json:"result_str,omitempty"`
}

func (m *LogoutRsp) Reset()                    { *m = LogoutRsp{} }
func (m *LogoutRsp) String() string            { return proto.CompactTextString(m) }
func (*LogoutRsp) ProtoMessage()               {}
func (*LogoutRsp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *LogoutRsp) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LogoutRsp) GetResultCode() ResultCode {
	if m != nil {
		return m.ResultCode
	}
	return ResultCode_RC_DEFAULT
}

func (m *LogoutRsp) GetResultStr() string {
	if m != nil {
		return m.ResultStr
	}
	return ""
}

type NinfoReq struct {
	Id uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *NinfoReq) Reset()                    { *m = NinfoReq{} }
func (m *NinfoReq) String() string            { return proto.CompactTextString(m) }
func (*NinfoReq) ProtoMessage()               {}
func (*NinfoReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *NinfoReq) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type NinfoRsp struct {
	Id    uint64     `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Nip   string     `protobuf:"bytes,2,opt,name=Nip" json:"Nip,omitempty"`
	Nport uint64     `protobuf:"varint,3,opt,name=Nport" json:"Nport,omitempty"`
	Rc    ResultCode `protobuf:"varint,4,opt,name=rc,enum=rpc.ResultCode" json:"rc,omitempty"`
}

func (m *NinfoRsp) Reset()                    { *m = NinfoRsp{} }
func (m *NinfoRsp) String() string            { return proto.CompactTextString(m) }
func (*NinfoRsp) ProtoMessage()               {}
func (*NinfoRsp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *NinfoRsp) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *NinfoRsp) GetNip() string {
	if m != nil {
		return m.Nip
	}
	return ""
}

func (m *NinfoRsp) GetNport() uint64 {
	if m != nil {
		return m.Nport
	}
	return 0
}

func (m *NinfoRsp) GetRc() ResultCode {
	if m != nil {
		return m.Rc
	}
	return ResultCode_RC_DEFAULT
}

type SendMsgReq struct {
	Id     uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Peerid uint64 `protobuf:"varint,2,opt,name=peerid" json:"peerid,omitempty"`
}

func (m *SendMsgReq) Reset()                    { *m = SendMsgReq{} }
func (m *SendMsgReq) String() string            { return proto.CompactTextString(m) }
func (*SendMsgReq) ProtoMessage()               {}
func (*SendMsgReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *SendMsgReq) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SendMsgReq) GetPeerid() uint64 {
	if m != nil {
		return m.Peerid
	}
	return 0
}

type SendMsgRsp struct {
	Id     uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Peerid uint64 `protobuf:"varint,2,opt,name=peerid" json:"peerid,omitempty"`
}

func (m *SendMsgRsp) Reset()                    { *m = SendMsgRsp{} }
func (m *SendMsgRsp) String() string            { return proto.CompactTextString(m) }
func (*SendMsgRsp) ProtoMessage()               {}
func (*SendMsgRsp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *SendMsgRsp) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SendMsgRsp) GetPeerid() uint64 {
	if m != nil {
		return m.Peerid
	}
	return 0
}

type MsgData struct {
	Id        uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	SessionId uint64 `protobuf:"varint,2,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	Content   string `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
}

func (m *MsgData) Reset()                    { *m = MsgData{} }
func (m *MsgData) String() string            { return proto.CompactTextString(m) }
func (*MsgData) ProtoMessage()               {}
func (*MsgData) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

func (m *MsgData) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MsgData) GetSessionId() uint64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *MsgData) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type MsgDataReadAck struct {
	ResultCode ResultCode `protobuf:"varint,1,opt,name=result_code,json=resultCode,enum=rpc.ResultCode" json:"result_code,omitempty"`
	ResultStr  string     `protobuf:"bytes,2,opt,name=result_str,json=resultStr" json:"result_str,omitempty"`
	Sip        string     `protobuf:"bytes,3,opt,name=Sip" json:"Sip,omitempty"`
	Sport      uint64     `protobuf:"varint,4,opt,name=Sport" json:"Sport,omitempty"`
}

func (m *MsgDataReadAck) Reset()                    { *m = MsgDataReadAck{} }
func (m *MsgDataReadAck) String() string            { return proto.CompactTextString(m) }
func (*MsgDataReadAck) ProtoMessage()               {}
func (*MsgDataReadAck) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

func (m *MsgDataReadAck) GetResultCode() ResultCode {
	if m != nil {
		return m.ResultCode
	}
	return ResultCode_RC_DEFAULT
}

func (m *MsgDataReadAck) GetResultStr() string {
	if m != nil {
		return m.ResultStr
	}
	return ""
}

func (m *MsgDataReadAck) GetSip() string {
	if m != nil {
		return m.Sip
	}
	return ""
}

func (m *MsgDataReadAck) GetSport() uint64 {
	if m != nil {
		return m.Sport
	}
	return 0
}

type UnreadMsgReq struct {
	Id uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *UnreadMsgReq) Reset()                    { *m = UnreadMsgReq{} }
func (m *UnreadMsgReq) String() string            { return proto.CompactTextString(m) }
func (*UnreadMsgReq) ProtoMessage()               {}
func (*UnreadMsgReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

func (m *UnreadMsgReq) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UnreadMsgInfo struct {
	Fromid    uint64 `protobuf:"varint,1,opt,name=fromid" json:"fromid,omitempty"`
	SessionId uint64 `protobuf:"varint,2,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	Content   string `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
}

func (m *UnreadMsgInfo) Reset()                    { *m = UnreadMsgInfo{} }
func (m *UnreadMsgInfo) String() string            { return proto.CompactTextString(m) }
func (*UnreadMsgInfo) ProtoMessage()               {}
func (*UnreadMsgInfo) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

func (m *UnreadMsgInfo) GetFromid() uint64 {
	if m != nil {
		return m.Fromid
	}
	return 0
}

func (m *UnreadMsgInfo) GetSessionId() uint64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *UnreadMsgInfo) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type UnreadMsgRsp struct {
	ResultCode    ResultCode       `protobuf:"varint,1,opt,name=result_code,json=resultCode,enum=rpc.ResultCode" json:"result_code,omitempty"`
	ResultStr     string           `protobuf:"bytes,2,opt,name=result_str,json=resultStr" json:"result_str,omitempty"`
	UnreadMsgList []*UnreadMsgInfo `protobuf:"bytes,3,rep,name=UnreadMsg_list,json=UnreadMsgList" json:"UnreadMsg_list,omitempty"`
	MsgCount      uint64           `protobuf:"varint,4,opt,name=msg_count,json=msgCount" json:"msg_count,omitempty"`
}

func (m *UnreadMsgRsp) Reset()                    { *m = UnreadMsgRsp{} }
func (m *UnreadMsgRsp) String() string            { return proto.CompactTextString(m) }
func (*UnreadMsgRsp) ProtoMessage()               {}
func (*UnreadMsgRsp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{14} }

func (m *UnreadMsgRsp) GetResultCode() ResultCode {
	if m != nil {
		return m.ResultCode
	}
	return ResultCode_RC_DEFAULT
}

func (m *UnreadMsgRsp) GetResultStr() string {
	if m != nil {
		return m.ResultStr
	}
	return ""
}

func (m *UnreadMsgRsp) GetUnreadMsgList() []*UnreadMsgInfo {
	if m != nil {
		return m.UnreadMsgList
	}
	return nil
}

func (m *UnreadMsgRsp) GetMsgCount() uint64 {
	if m != nil {
		return m.MsgCount
	}
	return 0
}

type CreateSessionReq struct {
	Fromid uint64 `protobuf:"varint,1,opt,name=fromid" json:"fromid,omitempty"`
	Peerid uint64 `protobuf:"varint,2,opt,name=peerid" json:"peerid,omitempty"`
}

func (m *CreateSessionReq) Reset()                    { *m = CreateSessionReq{} }
func (m *CreateSessionReq) String() string            { return proto.CompactTextString(m) }
func (*CreateSessionReq) ProtoMessage()               {}
func (*CreateSessionReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{15} }

func (m *CreateSessionReq) GetFromid() uint64 {
	if m != nil {
		return m.Fromid
	}
	return 0
}

func (m *CreateSessionReq) GetPeerid() uint64 {
	if m != nil {
		return m.Peerid
	}
	return 0
}

type CreateSessionRsp struct {
	Fromid     uint64     `protobuf:"varint,1,opt,name=fromid" json:"fromid,omitempty"`
	Peerid     uint64     `protobuf:"varint,2,opt,name=peerid" json:"peerid,omitempty"`
	SessionId  uint64     `protobuf:"varint,3,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	ResultCode ResultCode `protobuf:"varint,4,opt,name=result_code,json=resultCode,enum=rpc.ResultCode" json:"result_code,omitempty"`
	ResultStr  string     `protobuf:"bytes,5,opt,name=result_str,json=resultStr" json:"result_str,omitempty"`
	Sip        string     `protobuf:"bytes,6,opt,name=Sip" json:"Sip,omitempty"`
	Sport      uint64     `protobuf:"varint,7,opt,name=Sport" json:"Sport,omitempty"`
}

func (m *CreateSessionRsp) Reset()                    { *m = CreateSessionRsp{} }
func (m *CreateSessionRsp) String() string            { return proto.CompactTextString(m) }
func (*CreateSessionRsp) ProtoMessage()               {}
func (*CreateSessionRsp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{16} }

func (m *CreateSessionRsp) GetFromid() uint64 {
	if m != nil {
		return m.Fromid
	}
	return 0
}

func (m *CreateSessionRsp) GetPeerid() uint64 {
	if m != nil {
		return m.Peerid
	}
	return 0
}

func (m *CreateSessionRsp) GetSessionId() uint64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *CreateSessionRsp) GetResultCode() ResultCode {
	if m != nil {
		return m.ResultCode
	}
	return ResultCode_RC_DEFAULT
}

func (m *CreateSessionRsp) GetResultStr() string {
	if m != nil {
		return m.ResultStr
	}
	return ""
}

func (m *CreateSessionRsp) GetSip() string {
	if m != nil {
		return m.Sip
	}
	return ""
}

func (m *CreateSessionRsp) GetSport() uint64 {
	if m != nil {
		return m.Sport
	}
	return 0
}

type CloseSessionReq struct {
	Fromid    uint64 `protobuf:"varint,1,opt,name=fromid" json:"fromid,omitempty"`
	Peerid    uint64 `protobuf:"varint,2,opt,name=peerid" json:"peerid,omitempty"`
	SessionId uint64 `protobuf:"varint,3,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
}

func (m *CloseSessionReq) Reset()                    { *m = CloseSessionReq{} }
func (m *CloseSessionReq) String() string            { return proto.CompactTextString(m) }
func (*CloseSessionReq) ProtoMessage()               {}
func (*CloseSessionReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{17} }

func (m *CloseSessionReq) GetFromid() uint64 {
	if m != nil {
		return m.Fromid
	}
	return 0
}

func (m *CloseSessionReq) GetPeerid() uint64 {
	if m != nil {
		return m.Peerid
	}
	return 0
}

func (m *CloseSessionReq) GetSessionId() uint64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

type CloseSessionRsq struct {
	ResultCode ResultCode `protobuf:"varint,1,opt,name=result_code,json=resultCode,enum=rpc.ResultCode" json:"result_code,omitempty"`
	ResultStr  string     `protobuf:"bytes,2,opt,name=result_str,json=resultStr" json:"result_str,omitempty"`
}

func (m *CloseSessionRsq) Reset()                    { *m = CloseSessionRsq{} }
func (m *CloseSessionRsq) String() string            { return proto.CompactTextString(m) }
func (*CloseSessionRsq) ProtoMessage()               {}
func (*CloseSessionRsq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{18} }

func (m *CloseSessionRsq) GetResultCode() ResultCode {
	if m != nil {
		return m.ResultCode
	}
	return ResultCode_RC_DEFAULT
}

func (m *CloseSessionRsq) GetResultStr() string {
	if m != nil {
		return m.ResultStr
	}
	return ""
}

func init() {
	proto.RegisterType((*ServerTimeReq)(nil), "rpc.ServerTimeReq")
	proto.RegisterType((*ServerTimeRsp)(nil), "rpc.ServerTimeRsp")
	proto.RegisterType((*LoginReq)(nil), "rpc.LoginReq")
	proto.RegisterType((*LoginRsp)(nil), "rpc.LoginRsp")
	proto.RegisterType((*LogoutReq)(nil), "rpc.LogoutReq")
	proto.RegisterType((*LogoutRsp)(nil), "rpc.LogoutRsp")
	proto.RegisterType((*NinfoReq)(nil), "rpc.NinfoReq")
	proto.RegisterType((*NinfoRsp)(nil), "rpc.NinfoRsp")
	proto.RegisterType((*SendMsgReq)(nil), "rpc.SendMsgReq")
	proto.RegisterType((*SendMsgRsp)(nil), "rpc.SendMsgRsp")
	proto.RegisterType((*MsgData)(nil), "rpc.MsgData")
	proto.RegisterType((*MsgDataReadAck)(nil), "rpc.MsgDataReadAck")
	proto.RegisterType((*UnreadMsgReq)(nil), "rpc.UnreadMsgReq")
	proto.RegisterType((*UnreadMsgInfo)(nil), "rpc.UnreadMsgInfo")
	proto.RegisterType((*UnreadMsgRsp)(nil), "rpc.UnreadMsgRsp")
	proto.RegisterType((*CreateSessionReq)(nil), "rpc.CreateSessionReq")
	proto.RegisterType((*CreateSessionRsp)(nil), "rpc.CreateSessionRsp")
	proto.RegisterType((*CloseSessionReq)(nil), "rpc.CloseSessionReq")
	proto.RegisterType((*CloseSessionRsq)(nil), "rpc.CloseSessionRsq")
}

func init() { proto.RegisterFile("rpc/Clientmsg.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 558 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x95, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0x65, 0xc7, 0xfd, 0xf0, 0xb4, 0x4d, 0x8b, 0xa9, 0x50, 0xd4, 0xaa, 0xa5, 0xda, 0x53,
	0x4e, 0x29, 0x0a, 0x08, 0x89, 0x23, 0x4d, 0x2f, 0x95, 0xd2, 0x20, 0xad, 0xe1, 0xec, 0xba, 0xf6,
	0xc6, 0x5a, 0xea, 0xec, 0x6e, 0x76, 0x36, 0xf0, 0x0c, 0x3c, 0x11, 0xef, 0xc2, 0xd3, 0x20, 0x7f,
	0xc4, 0x49, 0x5d, 0x5b, 0x28, 0x50, 0x71, 0xdb, 0xff, 0x8c, 0xe7, 0xeb, 0x37, 0x23, 0x19, 0x5e,
	0x6a, 0x15, 0x5d, 0x8e, 0x52, 0xce, 0x84, 0x99, 0x61, 0x32, 0x50, 0x5a, 0x1a, 0xe9, 0x75, 0xb4,
	0x8a, 0x4e, 0x8e, 0x33, 0xcf, 0x55, 0x88, 0xec, 0x9a, 0x4d, 0xb9, 0x60, 0x85, 0x8b, 0x1c, 0xc2,
	0x81, 0xcf, 0xf4, 0x37, 0xa6, 0x3f, 0xf3, 0x19, 0xa3, 0x6c, 0x4e, 0x2e, 0x1f, 0x19, 0x50, 0x79,
	0xe7, 0x00, 0x2b, 0x43, 0xcf, 0xba, 0xb0, 0xfa, 0x0e, 0x5d, 0xb3, 0x90, 0xaf, 0xb0, 0x3b, 0x96,
	0x09, 0x17, 0x94, 0xcd, 0xbd, 0x2e, 0xd8, 0x3c, 0x2e, 0xbf, 0xb1, 0x79, 0xec, 0xbd, 0x82, 0x6d,
	0x15, 0x22, 0x7e, 0x8f, 0x7b, 0xf6, 0x85, 0xd5, 0x77, 0x69, 0xa9, 0xbc, 0xf7, 0x70, 0x20, 0x45,
	0xca, 0x05, 0x0b, 0xd0, 0x84, 0x66, 0xc1, 0x7a, 0x9d, 0x0b, 0xab, 0xdf, 0x1d, 0xbe, 0x18, 0x68,
	0x15, 0x0d, 0x3e, 0xe5, 0x1e, 0x3f, 0x73, 0x20, 0xdd, 0x97, 0x2b, 0xc5, 0xc8, 0xc3, 0xb2, 0x16,
	0xaa, 0x27, 0xb5, 0xde, 0xc0, 0x9e, 0x66, 0xb8, 0x48, 0x4d, 0x10, 0xc9, 0x98, 0xe5, 0x05, 0xbb,
	0xc3, 0xc3, 0x3c, 0x23, 0xcd, 0xed, 0x23, 0x19, 0x33, 0x0a, 0xba, 0x7a, 0x7b, 0x67, 0x50, 0xaa,
	0x00, 0x8d, 0xce, 0x5b, 0x70, 0xa9, 0x5b, 0x58, 0x7c, 0xa3, 0xc9, 0x29, 0xb8, 0x63, 0x99, 0xc8,
	0x85, 0x69, 0x98, 0x8c, 0xa4, 0x95, 0xf3, 0x7f, 0xb4, 0x72, 0x02, 0xbb, 0x13, 0x2e, 0xa6, 0xb2,
	0xa9, 0x93, 0x68, 0xe9, 0x6b, 0x68, 0xe4, 0x08, 0x3a, 0x13, 0xae, 0x4a, 0xf8, 0xd9, 0xd3, 0x3b,
	0x86, 0xad, 0x89, 0x92, 0xda, 0xe4, 0x35, 0x1c, 0x5a, 0x08, 0xef, 0x35, 0xd8, 0x3a, 0xea, 0x39,
	0xcd, 0x7d, 0xda, 0x3a, 0x22, 0xef, 0xb2, 0x23, 0x10, 0xf1, 0x2d, 0x26, 0x6d, 0x6b, 0x66, 0x4c,
	0xf3, 0x62, 0xcd, 0x0e, 0x2d, 0xd5, 0x7a, 0x54, 0x43, 0x73, 0x6d, 0x51, 0x14, 0x76, 0x6e, 0x31,
	0xb9, 0x0e, 0x4d, 0xf8, 0x24, 0xe4, 0x0c, 0x00, 0x19, 0x22, 0x97, 0x22, 0xa8, 0xc2, 0xdc, 0xd2,
	0x72, 0x13, 0x7b, 0x3d, 0xd8, 0x89, 0xa4, 0x30, 0x4c, 0x98, 0x12, 0xe1, 0x52, 0x92, 0x1f, 0x16,
	0x74, 0xcb, 0xa4, 0x94, 0x85, 0xf1, 0xc7, 0xe8, 0xa1, 0xbe, 0x24, 0x6b, 0xd3, 0x25, 0xd9, 0xb5,
	0x25, 0x65, 0xb0, 0x7d, 0xae, 0xca, 0xca, 0xd9, 0x33, 0x83, 0xed, 0xe7, 0xb0, 0x9d, 0x02, 0x76,
	0x2e, 0xc8, 0x39, 0xec, 0x7f, 0x11, 0x9a, 0x85, 0x2d, 0x34, 0xc9, 0x1d, 0x1c, 0x54, 0xfe, 0x1b,
	0x31, 0x95, 0x19, 0xa8, 0xa9, 0x96, 0xb3, 0xea, 0xa3, 0x52, 0xfd, 0x3d, 0x8d, 0x9f, 0xd6, 0x7a,
	0x0b, 0xa8, 0x9e, 0x9f, 0xc5, 0x07, 0xe8, 0x56, 0x05, 0x82, 0x94, 0x63, 0xd6, 0x42, 0xa7, 0xbf,
	0x37, 0xf4, 0xf2, 0x9c, 0x8f, 0xc6, 0xa3, 0xab, 0x69, 0xc7, 0x1c, 0x8d, 0x77, 0x0a, 0xee, 0x0c,
	0x93, 0x20, 0x92, 0x0b, 0xb1, 0x04, 0xb7, 0x3b, 0xc3, 0x64, 0x94, 0x69, 0x72, 0x05, 0x47, 0x23,
	0xcd, 0x42, 0xc3, 0xfc, 0x62, 0xcc, 0x8c, 0x5f, 0x1b, 0x9e, 0xb6, 0xfb, 0xfa, 0x65, 0xd5, 0x93,
	0xa0, 0xda, 0x34, 0x49, 0x8d, 0x7d, 0xa7, 0xce, 0xbe, 0x06, 0xd4, 0xd9, 0x14, 0xe8, 0x56, 0xcb,
	0x71, 0x6d, 0x37, 0x1c, 0xd7, 0xce, 0xfa, 0x71, 0xdd, 0xc1, 0xe1, 0x28, 0x95, 0xf8, 0x0f, 0x7c,
	0xfe, 0x30, 0x1a, 0xb9, 0xaf, 0x55, 0xc0, 0xf9, 0xb3, 0x9f, 0xcf, 0xfd, 0x76, 0xfe, 0x73, 0x7a,
	0xfb, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xfa, 0xc5, 0x72, 0xc7, 0xce, 0x06, 0x00, 0x00,
}
