// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/Clientmsg.proto

/*
Package rpc is a generated protocol buffer package.

It is generated from these files:
	rpc/Clientmsg.proto
	rpc/DNmsg.proto

It has these top-level messages:
	ServerTimeReq
	ServerTimeRsp
	Ninfo
*/
package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ServerTimeReq struct {
}

func (m *ServerTimeReq) Reset()                    { *m = ServerTimeReq{} }
func (m *ServerTimeReq) String() string            { return proto.CompactTextString(m) }
func (*ServerTimeReq) ProtoMessage()               {}
func (*ServerTimeReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ServerTimeRsp struct {
	ServerTime uint64 `protobuf:"varint,1,opt,name=ServerTime" json:"ServerTime,omitempty"`
}

func (m *ServerTimeRsp) Reset()                    { *m = ServerTimeRsp{} }
func (m *ServerTimeRsp) String() string            { return proto.CompactTextString(m) }
func (*ServerTimeRsp) ProtoMessage()               {}
func (*ServerTimeRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ServerTimeRsp) GetServerTime() uint64 {
	if m != nil {
		return m.ServerTime
	}
	return 0
}

func init() {
	proto.RegisterType((*ServerTimeReq)(nil), "rpc.ServerTimeReq")
	proto.RegisterType((*ServerTimeRsp)(nil), "rpc.ServerTimeRsp")
}

func init() { proto.RegisterFile("rpc/Clientmsg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 93 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x2a, 0x48, 0xd6,
	0x77, 0xce, 0xc9, 0x4c, 0xcd, 0x2b, 0xc9, 0x2d, 0x4e, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x62, 0x2e, 0x2a, 0x48, 0x56, 0xe2, 0xe7, 0xe2, 0x0d, 0x4e, 0x2d, 0x2a, 0x4b, 0x2d, 0x0a, 0xc9,
	0xcc, 0x4d, 0x0d, 0x4a, 0x2d, 0x54, 0xd2, 0x47, 0x11, 0x28, 0x2e, 0x10, 0x92, 0xe3, 0xe2, 0x42,
	0x08, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x04, 0x21, 0x89, 0x24, 0xb1, 0x81, 0x4d, 0x33, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x3a, 0xfc, 0x9a, 0x56, 0x64, 0x00, 0x00, 0x00,
}
