// Code generated by protoc-gen-go. DO NOT EDIT.
// source: RpcService.proto

package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type NinfoReq struct {
	Id uint64 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
}

func (m *NinfoReq) Reset()                    { *m = NinfoReq{} }
func (m *NinfoReq) String() string            { return proto.CompactTextString(m) }
func (*NinfoReq) ProtoMessage()               {}
func (*NinfoReq) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *NinfoReq) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type NinfoRsp struct {
	Id    uint64     `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Nip   string     `protobuf:"bytes,2,opt,name=Nip" json:"Nip,omitempty"`
	Nport uint64     `protobuf:"varint,3,opt,name=Nport" json:"Nport,omitempty"`
	Rc    ResultCode `protobuf:"varint,4,opt,name=rc,enum=rpc.ResultCode" json:"rc,omitempty"`
}

func (m *NinfoRsp) Reset()                    { *m = NinfoRsp{} }
func (m *NinfoRsp) String() string            { return proto.CompactTextString(m) }
func (*NinfoRsp) ProtoMessage()               {}
func (*NinfoRsp) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *NinfoRsp) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *NinfoRsp) GetNip() string {
	if m != nil {
		return m.Nip
	}
	return ""
}

func (m *NinfoRsp) GetNport() uint64 {
	if m != nil {
		return m.Nport
	}
	return 0
}

func (m *NinfoRsp) GetRc() ResultCode {
	if m != nil {
		return m.Rc
	}
	return ResultCode_RC_DEFAULT
}

func init() {
	proto.RegisterType((*NinfoReq)(nil), "rpc.NinfoReq")
	proto.RegisterType((*NinfoRsp)(nil), "rpc.NinfoRsp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for DService service

type DServiceClient interface {
	// Sends a greeting
	GetMyNserver(ctx context.Context, in *NinfoReq, opts ...grpc.CallOption) (*NinfoRsp, error)
}

type dServiceClient struct {
	cc *grpc.ClientConn
}

func NewDServiceClient(cc *grpc.ClientConn) DServiceClient {
	return &dServiceClient{cc}
}

func (c *dServiceClient) GetMyNserver(ctx context.Context, in *NinfoReq, opts ...grpc.CallOption) (*NinfoRsp, error) {
	out := new(NinfoRsp)
	err := grpc.Invoke(ctx, "/rpc.DService/GetMyNserver", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DService service

type DServiceServer interface {
	// Sends a greeting
	GetMyNserver(context.Context, *NinfoReq) (*NinfoRsp, error)
}

func RegisterDServiceServer(s *grpc.Server, srv DServiceServer) {
	s.RegisterService(&_DService_serviceDesc, srv)
}

func _DService_GetMyNserver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NinfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DServiceServer).GetMyNserver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.DService/GetMyNserver",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DServiceServer).GetMyNserver(ctx, req.(*NinfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _DService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.DService",
	HandlerType: (*DServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMyNserver",
			Handler:    _DService_GetMyNserver_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "RpcService.proto",
}

func init() { proto.RegisterFile("RpcService.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x4d, 0xba, 0xca, 0x3a, 0xe8, 0x5a, 0x82, 0x87, 0xd0, 0x8b, 0xa5, 0xa7, 0x9e, 0x72,
	0x58, 0x6f, 0x1e, 0xb5, 0x20, 0x3d, 0x98, 0x43, 0x7c, 0x02, 0x4d, 0xa7, 0x10, 0x90, 0x66, 0x9c,
	0xc4, 0x82, 0x6f, 0x2f, 0xd6, 0x16, 0x64, 0x6f, 0xf3, 0xcf, 0x37, 0x03, 0xdf, 0x0f, 0xa5, 0x23,
	0xff, 0x8a, 0x3c, 0x07, 0x8f, 0x86, 0x38, 0xe6, 0xa8, 0x0a, 0x26, 0x5f, 0x95, 0x8f, 0x6f, 0x09,
	0x3b, 0x1c, 0xc3, 0xb4, 0xae, 0x9b, 0x0a, 0xf6, 0x36, 0x4c, 0x63, 0x74, 0xf8, 0xa9, 0x0e, 0x20,
	0xfb, 0x41, 0x8b, 0x5a, 0xb4, 0x3b, 0x27, 0xfb, 0xa1, 0xf1, 0x1b, 0x4b, 0x74, 0xca, 0x54, 0x09,
	0x85, 0x0d, 0xa4, 0x65, 0x2d, 0xda, 0x4b, 0xf7, 0x3b, 0xaa, 0x5b, 0x38, 0xb7, 0x14, 0x39, 0xeb,
	0x62, 0x39, 0xfa, 0x0b, 0xea, 0x0e, 0x24, 0x7b, 0xbd, 0xab, 0x45, 0x7b, 0x38, 0xde, 0x18, 0x26,
	0x6f, 0x1c, 0xa6, 0xaf, 0x8f, 0xfc, 0x14, 0x07, 0x74, 0x92, 0xfd, 0xf1, 0x01, 0xf6, 0xdd, 0x6a,
	0xaa, 0x0c, 0x5c, 0x3d, 0x63, 0x7e, 0xf9, 0xb6, 0x09, 0x79, 0x46, 0x56, 0xd7, 0xcb, 0xc3, 0xe6,
	0x57, 0xfd, 0x8f, 0x89, 0x9a, 0xb3, 0xf7, 0x8b, 0xa5, 0xc3, 0xfd, 0x4f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x80, 0xd9, 0x74, 0x2c, 0xee, 0x00, 0x00, 0x00,
}
